// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `libshout`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class LibShout {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  LibShout(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  LibShout.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// initializes the shout library. Must be called before anything else
  void shout_init() {
    return _shout_init();
  }

  late final _shout_initPtr = _lookup<ffi.NativeFunction<ffi.Void Function()>>(
    'shout_init',
  );
  late final _shout_init = _shout_initPtr.asFunction<void Function()>();

  /// shuts down the shout library, deallocating any global storage. Don't call
  /// anything afterwards
  void shout_shutdown() {
    return _shout_shutdown();
  }

  late final _shout_shutdownPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('shout_shutdown');
  late final _shout_shutdown = _shout_shutdownPtr.asFunction<void Function()>();

  /// returns a static version string.  Non-null parameters will be set to the
  /// value of the library major, minor, and patch levels, respectively
  ffi.Pointer<ffi.Char> shout_version(
    ffi.Pointer<ffi.Int> major,
    ffi.Pointer<ffi.Int> minor,
    ffi.Pointer<ffi.Int> patch,
  ) {
    return _shout_version(major, minor, patch);
  }

  late final _shout_versionPtr = _lookup<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Char> Function(
        ffi.Pointer<ffi.Int>,
        ffi.Pointer<ffi.Int>,
        ffi.Pointer<ffi.Int>,
      )
    >
  >('shout_version');
  late final _shout_version =
      _shout_versionPtr
          .asFunction<
            ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<ffi.Int>,
              ffi.Pointer<ffi.Int>,
              ffi.Pointer<ffi.Int>,
            )
          >();

  /// Allocates and sets up a new shout_t.  Returns NULL if it can't get enough
  /// memory.  The returns shout_t must be disposed of with shout_free.
  ffi.Pointer<shout_t> shout_new() {
    return _shout_new();
  }

  late final _shout_newPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<shout_t> Function()>>('shout_new');
  late final _shout_new =
      _shout_newPtr.asFunction<ffi.Pointer<shout_t> Function()>();

  /// Free all memory allocated by a shout_t
  void shout_free(ffi.Pointer<shout_t> self) {
    return _shout_free(self);
  }

  late final _shout_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<shout_t>)>>(
        'shout_free',
      );
  late final _shout_free =
      _shout_freePtr.asFunction<void Function(ffi.Pointer<shout_t>)>();

  /// Returns a statically allocated string describing the last shout error
  /// to occur.  Only valid until the next libshout call on this shout_t
  ffi.Pointer<ffi.Char> shout_get_error(ffi.Pointer<shout_t> self) {
    return _shout_get_error(self);
  }

  late final _shout_get_errorPtr = _lookup<
    ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>
  >('shout_get_error');
  late final _shout_get_error =
      _shout_get_errorPtr
          .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>();

  /// Return the error code (e.g. SHOUTERR_SOCKET) for this shout instance
  int shout_get_errno(ffi.Pointer<shout_t> self) {
    return _shout_get_errno(self);
  }

  late final _shout_get_errnoPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<shout_t>)>>(
        'shout_get_errno',
      );
  late final _shout_get_errno =
      _shout_get_errnoPtr.asFunction<int Function(ffi.Pointer<shout_t>)>();

  /// returns SHOUTERR_CONNECTED or SHOUTERR_UNCONNECTED
  int shout_get_connected(ffi.Pointer<shout_t> self) {
    return _shout_get_connected(self);
  }

  late final _shout_get_connectedPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<shout_t>)>>(
        'shout_get_connected',
      );
  late final _shout_get_connected =
      _shout_get_connectedPtr.asFunction<int Function(ffi.Pointer<shout_t>)>();

  /// Connection parameters
  int shout_set_host(ffi.Pointer<shout_t> self, ffi.Pointer<ffi.Char> host) {
    return _shout_set_host(self, host);
  }

  late final _shout_set_hostPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<shout_t>, ffi.Pointer<ffi.Char>)
    >
  >('shout_set_host');
  late final _shout_set_host =
      _shout_set_hostPtr
          .asFunction<
            int Function(ffi.Pointer<shout_t>, ffi.Pointer<ffi.Char>)
          >();

  ffi.Pointer<ffi.Char> shout_get_host(ffi.Pointer<shout_t> self) {
    return _shout_get_host(self);
  }

  late final _shout_get_hostPtr = _lookup<
    ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>
  >('shout_get_host');
  late final _shout_get_host =
      _shout_get_hostPtr
          .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>();

  int shout_set_port(ffi.Pointer<shout_t> self, int port) {
    return _shout_set_port(self, port);
  }

  late final _shout_set_portPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<shout_t>, ffi.UnsignedShort)
    >
  >('shout_set_port');
  late final _shout_set_port =
      _shout_set_portPtr.asFunction<int Function(ffi.Pointer<shout_t>, int)>();

  int shout_get_port(ffi.Pointer<shout_t> self) {
    return _shout_get_port(self);
  }

  late final _shout_get_portPtr = _lookup<
    ffi.NativeFunction<ffi.UnsignedShort Function(ffi.Pointer<shout_t>)>
  >('shout_get_port');
  late final _shout_get_port =
      _shout_get_portPtr.asFunction<int Function(ffi.Pointer<shout_t>)>();

  int shout_set_agent(ffi.Pointer<shout_t> self, ffi.Pointer<ffi.Char> agent) {
    return _shout_set_agent(self, agent);
  }

  late final _shout_set_agentPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<shout_t>, ffi.Pointer<ffi.Char>)
    >
  >('shout_set_agent');
  late final _shout_set_agent =
      _shout_set_agentPtr
          .asFunction<
            int Function(ffi.Pointer<shout_t>, ffi.Pointer<ffi.Char>)
          >();

  ffi.Pointer<ffi.Char> shout_get_agent(ffi.Pointer<shout_t> self) {
    return _shout_get_agent(self);
  }

  late final _shout_get_agentPtr = _lookup<
    ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>
  >('shout_get_agent');
  late final _shout_get_agent =
      _shout_get_agentPtr
          .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>();

  /// See SHOUT_TLS_* above
  int shout_set_tls(ffi.Pointer<shout_t> self, int mode) {
    return _shout_set_tls(self, mode);
  }

  late final _shout_set_tlsPtr = _lookup<
    ffi.NativeFunction<ffi.Int Function(ffi.Pointer<shout_t>, ffi.Int)>
  >('shout_set_tls');
  late final _shout_set_tls =
      _shout_set_tlsPtr.asFunction<int Function(ffi.Pointer<shout_t>, int)>();

  int shout_get_tls(ffi.Pointer<shout_t> self) {
    return _shout_get_tls(self);
  }

  late final _shout_get_tlsPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<shout_t>)>>(
        'shout_get_tls',
      );
  late final _shout_get_tls =
      _shout_get_tlsPtr.asFunction<int Function(ffi.Pointer<shout_t>)>();

  /// Set the directory for CA certs. Default: operating system's default
  int shout_set_ca_directory(
    ffi.Pointer<shout_t> self,
    ffi.Pointer<ffi.Char> directory,
  ) {
    return _shout_set_ca_directory(self, directory);
  }

  late final _shout_set_ca_directoryPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<shout_t>, ffi.Pointer<ffi.Char>)
    >
  >('shout_set_ca_directory');
  late final _shout_set_ca_directory =
      _shout_set_ca_directoryPtr
          .asFunction<
            int Function(ffi.Pointer<shout_t>, ffi.Pointer<ffi.Char>)
          >();

  ffi.Pointer<ffi.Char> shout_get_ca_directory(ffi.Pointer<shout_t> self) {
    return _shout_get_ca_directory(self);
  }

  late final _shout_get_ca_directoryPtr = _lookup<
    ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>
  >('shout_get_ca_directory');
  late final _shout_get_ca_directory =
      _shout_get_ca_directoryPtr
          .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>();

  /// Set a CA cert file for checking. If you use a self signed server cert
  /// you can pass this cert using this function for verification.
  /// Default: operating system's default
  int shout_set_ca_file(ffi.Pointer<shout_t> self, ffi.Pointer<ffi.Char> file) {
    return _shout_set_ca_file(self, file);
  }

  late final _shout_set_ca_filePtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<shout_t>, ffi.Pointer<ffi.Char>)
    >
  >('shout_set_ca_file');
  late final _shout_set_ca_file =
      _shout_set_ca_filePtr
          .asFunction<
            int Function(ffi.Pointer<shout_t>, ffi.Pointer<ffi.Char>)
          >();

  ffi.Pointer<ffi.Char> shout_get_ca_file(ffi.Pointer<shout_t> self) {
    return _shout_get_ca_file(self);
  }

  late final _shout_get_ca_filePtr = _lookup<
    ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>
  >('shout_get_ca_file');
  late final _shout_get_ca_file =
      _shout_get_ca_filePtr
          .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>();

  /// Set list of allowed ciphers.
  /// This function should only be used in case of using an old libshout
  /// after some attacks got known. Watch the icecast mailinglist for
  /// known problems.
  /// DO NOT SET THIS TO ANY FIXED VALUE. IF YOU USE THIS FUNCTION
  /// EXPOSE IT TO THE USER. OTHERWISE YOU WILL HARM SECURITY.
  /// Default: internal list of secure ciphers.
  int shout_set_allowed_ciphers(
    ffi.Pointer<shout_t> self,
    ffi.Pointer<ffi.Char> ciphers,
  ) {
    return _shout_set_allowed_ciphers(self, ciphers);
  }

  late final _shout_set_allowed_ciphersPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<shout_t>, ffi.Pointer<ffi.Char>)
    >
  >('shout_set_allowed_ciphers');
  late final _shout_set_allowed_ciphers =
      _shout_set_allowed_ciphersPtr
          .asFunction<
            int Function(ffi.Pointer<shout_t>, ffi.Pointer<ffi.Char>)
          >();

  ffi.Pointer<ffi.Char> shout_get_allowed_ciphers(ffi.Pointer<shout_t> self) {
    return _shout_get_allowed_ciphers(self);
  }

  late final _shout_get_allowed_ciphersPtr = _lookup<
    ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>
  >('shout_get_allowed_ciphers');
  late final _shout_get_allowed_ciphers =
      _shout_get_allowed_ciphersPtr
          .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>();

  /// Authentication parameters
  int shout_set_user(
    ffi.Pointer<shout_t> self,
    ffi.Pointer<ffi.Char> username,
  ) {
    return _shout_set_user(self, username);
  }

  late final _shout_set_userPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<shout_t>, ffi.Pointer<ffi.Char>)
    >
  >('shout_set_user');
  late final _shout_set_user =
      _shout_set_userPtr
          .asFunction<
            int Function(ffi.Pointer<shout_t>, ffi.Pointer<ffi.Char>)
          >();

  ffi.Pointer<ffi.Char> shout_get_user(ffi.Pointer<shout_t> self) {
    return _shout_get_user(self);
  }

  late final _shout_get_userPtr = _lookup<
    ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>
  >('shout_get_user');
  late final _shout_get_user =
      _shout_get_userPtr
          .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>();

  int shout_set_password(
    ffi.Pointer<shout_t> arg0,
    ffi.Pointer<ffi.Char> password,
  ) {
    return _shout_set_password(arg0, password);
  }

  late final _shout_set_passwordPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<shout_t>, ffi.Pointer<ffi.Char>)
    >
  >('shout_set_password');
  late final _shout_set_password =
      _shout_set_passwordPtr
          .asFunction<
            int Function(ffi.Pointer<shout_t>, ffi.Pointer<ffi.Char>)
          >();

  ffi.Pointer<ffi.Char> shout_get_password(ffi.Pointer<shout_t> self) {
    return _shout_get_password(self);
  }

  late final _shout_get_passwordPtr = _lookup<
    ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>
  >('shout_get_password');
  late final _shout_get_password =
      _shout_get_passwordPtr
          .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>();

  /// Set a client certificate for TLS connections.
  /// This must be in PEM format with both cert and private key in the same file.
  /// Default: none.
  int shout_set_client_certificate(
    ffi.Pointer<shout_t> self,
    ffi.Pointer<ffi.Char> certificate,
  ) {
    return _shout_set_client_certificate(self, certificate);
  }

  late final _shout_set_client_certificatePtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<shout_t>, ffi.Pointer<ffi.Char>)
    >
  >('shout_set_client_certificate');
  late final _shout_set_client_certificate =
      _shout_set_client_certificatePtr
          .asFunction<
            int Function(ffi.Pointer<shout_t>, ffi.Pointer<ffi.Char>)
          >();

  ffi.Pointer<ffi.Char> shout_get_client_certificate(
    ffi.Pointer<shout_t> self,
  ) {
    return _shout_get_client_certificate(self);
  }

  late final _shout_get_client_certificatePtr = _lookup<
    ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>
  >('shout_get_client_certificate');
  late final _shout_get_client_certificate =
      _shout_get_client_certificatePtr
          .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>();

  /// Mount parameters
  int shout_set_mount(ffi.Pointer<shout_t> self, ffi.Pointer<ffi.Char> mount) {
    return _shout_set_mount(self, mount);
  }

  late final _shout_set_mountPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<shout_t>, ffi.Pointer<ffi.Char>)
    >
  >('shout_set_mount');
  late final _shout_set_mount =
      _shout_set_mountPtr
          .asFunction<
            int Function(ffi.Pointer<shout_t>, ffi.Pointer<ffi.Char>)
          >();

  ffi.Pointer<ffi.Char> shout_get_mount(ffi.Pointer<shout_t> self) {
    return _shout_get_mount(self);
  }

  late final _shout_get_mountPtr = _lookup<
    ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>
  >('shout_get_mount');
  late final _shout_get_mount =
      _shout_get_mountPtr
          .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>();

  /// Other parameters */
  /// /* takes a SHOUT_AI_xxxx argument
  int shout_set_audio_info(
    ffi.Pointer<shout_t> self,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Char> value,
  ) {
    return _shout_set_audio_info(self, name, value);
  }

  late final _shout_set_audio_infoPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<shout_t>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
      )
    >
  >('shout_set_audio_info');
  late final _shout_set_audio_info =
      _shout_set_audio_infoPtr
          .asFunction<
            int Function(
              ffi.Pointer<shout_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
            )
          >();

  ffi.Pointer<ffi.Char> shout_get_audio_info(
    ffi.Pointer<shout_t> self,
    ffi.Pointer<ffi.Char> name,
  ) {
    return _shout_get_audio_info(self, name);
  }

  late final _shout_get_audio_infoPtr = _lookup<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Char> Function(
        ffi.Pointer<shout_t>,
        ffi.Pointer<ffi.Char>,
      )
    >
  >('shout_get_audio_info');
  late final _shout_get_audio_info =
      _shout_get_audio_infoPtr
          .asFunction<
            ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<shout_t>,
              ffi.Pointer<ffi.Char>,
            )
          >();

  /// takes a SHOUT_META_xxxx argument
  int shout_set_meta(
    ffi.Pointer<shout_t> self,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Char> value,
  ) {
    return _shout_set_meta(self, name, value);
  }

  late final _shout_set_metaPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<shout_t>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
      )
    >
  >('shout_set_meta');
  late final _shout_set_meta =
      _shout_set_metaPtr
          .asFunction<
            int Function(
              ffi.Pointer<shout_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
            )
          >();

  ffi.Pointer<ffi.Char> shout_get_meta(
    ffi.Pointer<shout_t> self,
    ffi.Pointer<ffi.Char> name,
  ) {
    return _shout_get_meta(self, name);
  }

  late final _shout_get_metaPtr = _lookup<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Char> Function(
        ffi.Pointer<shout_t>,
        ffi.Pointer<ffi.Char>,
      )
    >
  >('shout_get_meta');
  late final _shout_get_meta =
      _shout_get_metaPtr
          .asFunction<
            ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<shout_t>,
              ffi.Pointer<ffi.Char>,
            )
          >();

  int shout_set_public(ffi.Pointer<shout_t> self, int make_public) {
    return _shout_set_public(self, make_public);
  }

  late final _shout_set_publicPtr = _lookup<
    ffi.NativeFunction<ffi.Int Function(ffi.Pointer<shout_t>, ffi.UnsignedInt)>
  >('shout_set_public');
  late final _shout_set_public =
      _shout_set_publicPtr
          .asFunction<int Function(ffi.Pointer<shout_t>, int)>();

  int shout_get_public(ffi.Pointer<shout_t> self) {
    return _shout_get_public(self);
  }

  late final _shout_get_publicPtr = _lookup<
    ffi.NativeFunction<ffi.UnsignedInt Function(ffi.Pointer<shout_t>)>
  >('shout_get_public');
  late final _shout_get_public =
      _shout_get_publicPtr.asFunction<int Function(ffi.Pointer<shout_t>)>();

  /// Set the content language.
  /// Values as per RFC5646 Section 2.1.
  /// This lists the target audiance language(s), not the language of songs
  /// (unless the station has a focus on songs in a specific language).
  /// The value of NULL is allowed if the content language is not known or is expected to change.
  ///
  /// Examples:
  /// A German station with moderations and news in German and Gamern and international songs
  /// would generally set this to "de-DE".
  /// A similar station in Switzerland would set this to "de-CH".
  /// A station with content in Portuguese, and Klingon should set this to "pt, tlh".
  int shout_set_content_language(
    ffi.Pointer<shout_t> self,
    ffi.Pointer<ffi.Char> content_language,
  ) {
    return _shout_set_content_language(self, content_language);
  }

  late final _shout_set_content_languagePtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<shout_t>, ffi.Pointer<ffi.Char>)
    >
  >('shout_set_content_language');
  late final _shout_set_content_language =
      _shout_set_content_languagePtr
          .asFunction<
            int Function(ffi.Pointer<shout_t>, ffi.Pointer<ffi.Char>)
          >();

  ffi.Pointer<ffi.Char> shout_get_content_language(ffi.Pointer<shout_t> self) {
    return _shout_get_content_language(self);
  }

  late final _shout_get_content_languagePtr = _lookup<
    ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>
  >('shout_get_content_language');
  late final _shout_get_content_language =
      _shout_get_content_languagePtr
          .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>();

  /// Set the format of the content to send.
  /// * format is one of SHOUT_FORMAT_xxxx.
  /// * usage is a bit vector composed of SHOUT_USAGE_xxxx.
  /// * codecs is NULL as of this version. Future versions will also support NULL.
  int shout_set_content_format(
    ffi.Pointer<shout_t> self,
    int format,
    int usage,
    ffi.Pointer<ffi.Char> codecs,
  ) {
    return _shout_set_content_format(self, format, usage, codecs);
  }

  late final _shout_set_content_formatPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<shout_t>,
        ffi.UnsignedInt,
        ffi.UnsignedInt,
        ffi.Pointer<ffi.Char>,
      )
    >
  >('shout_set_content_format');
  late final _shout_set_content_format =
      _shout_set_content_formatPtr
          .asFunction<
            int Function(ffi.Pointer<shout_t>, int, int, ffi.Pointer<ffi.Char>)
          >();

  int shout_get_content_format(
    ffi.Pointer<shout_t> self,
    ffi.Pointer<ffi.UnsignedInt> format,
    ffi.Pointer<ffi.UnsignedInt> usage,
    ffi.Pointer<ffi.Pointer<ffi.Char>> codecs,
  ) {
    return _shout_get_content_format(self, format, usage, codecs);
  }

  late final _shout_get_content_formatPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<shout_t>,
        ffi.Pointer<ffi.UnsignedInt>,
        ffi.Pointer<ffi.UnsignedInt>,
        ffi.Pointer<ffi.Pointer<ffi.Char>>,
      )
    >
  >('shout_get_content_format');
  late final _shout_get_content_format =
      _shout_get_content_formatPtr
          .asFunction<
            int Function(
              ffi.Pointer<shout_t>,
              ffi.Pointer<ffi.UnsignedInt>,
              ffi.Pointer<ffi.UnsignedInt>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  /// takes a SHOUT_PROTOCOL_xxxxx argument
  int shout_set_protocol(ffi.Pointer<shout_t> self, int protocol) {
    return _shout_set_protocol(self, protocol);
  }

  late final _shout_set_protocolPtr = _lookup<
    ffi.NativeFunction<ffi.Int Function(ffi.Pointer<shout_t>, ffi.UnsignedInt)>
  >('shout_set_protocol');
  late final _shout_set_protocol =
      _shout_set_protocolPtr
          .asFunction<int Function(ffi.Pointer<shout_t>, int)>();

  int shout_get_protocol(ffi.Pointer<shout_t> self) {
    return _shout_get_protocol(self);
  }

  late final _shout_get_protocolPtr = _lookup<
    ffi.NativeFunction<ffi.UnsignedInt Function(ffi.Pointer<shout_t>)>
  >('shout_get_protocol');
  late final _shout_get_protocol =
      _shout_get_protocolPtr.asFunction<int Function(ffi.Pointer<shout_t>)>();

  /// Instructs libshout to use nonblocking I/O. Must be called before
  /// shout_open (no switching back and forth midstream at the moment).
  /// nonblocking is one of SHOUT_BLOCKING_xxx.
  int shout_set_nonblocking(ffi.Pointer<shout_t> self, int nonblocking) {
    return _shout_set_nonblocking(self, nonblocking);
  }

  late final _shout_set_nonblockingPtr = _lookup<
    ffi.NativeFunction<ffi.Int Function(ffi.Pointer<shout_t>, ffi.UnsignedInt)>
  >('shout_set_nonblocking');
  late final _shout_set_nonblocking =
      _shout_set_nonblockingPtr
          .asFunction<int Function(ffi.Pointer<shout_t>, int)>();

  int shout_get_nonblocking(ffi.Pointer<shout_t> self) {
    return _shout_get_nonblocking(self);
  }

  late final _shout_get_nonblockingPtr = _lookup<
    ffi.NativeFunction<ffi.UnsignedInt Function(ffi.Pointer<shout_t>)>
  >('shout_get_nonblocking');
  late final _shout_get_nonblocking =
      _shout_get_nonblockingPtr
          .asFunction<int Function(ffi.Pointer<shout_t>)>();

  /// Opens a connection to the server.  All parameters must already be set
  int shout_open(ffi.Pointer<shout_t> self) {
    return _shout_open(self);
  }

  late final _shout_openPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<shout_t>)>>(
        'shout_open',
      );
  late final _shout_open =
      _shout_openPtr.asFunction<int Function(ffi.Pointer<shout_t>)>();

  /// Closes a connection to the server
  int shout_close(ffi.Pointer<shout_t> self) {
    return _shout_close(self);
  }

  late final _shout_closePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<shout_t>)>>(
        'shout_close',
      );
  late final _shout_close =
      _shout_closePtr.asFunction<int Function(ffi.Pointer<shout_t>)>();

  /// Send data to the server, parsing it for format specific timing info
  int shout_send(
    ffi.Pointer<shout_t> self,
    ffi.Pointer<ffi.UnsignedChar> data,
    int len,
  ) {
    return _shout_send(self, data, len);
  }

  late final _shout_sendPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<shout_t>,
        ffi.Pointer<ffi.UnsignedChar>,
        ffi.Size,
      )
    >
  >('shout_send');
  late final _shout_send =
      _shout_sendPtr
          .asFunction<
            int Function(
              ffi.Pointer<shout_t>,
              ffi.Pointer<ffi.UnsignedChar>,
              int,
            )
          >();

  /// Send unparsed data to the server.  Do not use this unless you know
  /// what you are doing.
  /// Returns the number of bytes written, or < 0 on error.
  int shout_send_raw(
    ffi.Pointer<shout_t> self,
    ffi.Pointer<ffi.UnsignedChar> data,
    int len,
  ) {
    return _shout_send_raw(self, data, len);
  }

  late final _shout_send_rawPtr = _lookup<
    ffi.NativeFunction<
      ssize_t Function(
        ffi.Pointer<shout_t>,
        ffi.Pointer<ffi.UnsignedChar>,
        ffi.Size,
      )
    >
  >('shout_send_raw');
  late final _shout_send_raw =
      _shout_send_rawPtr
          .asFunction<
            int Function(
              ffi.Pointer<shout_t>,
              ffi.Pointer<ffi.UnsignedChar>,
              int,
            )
          >();

  /// return the number of bytes currently on the write queue (only makes sense in
  /// nonblocking mode).
  int shout_queuelen(ffi.Pointer<shout_t> self) {
    return _shout_queuelen(self);
  }

  late final _shout_queuelenPtr =
      _lookup<ffi.NativeFunction<ssize_t Function(ffi.Pointer<shout_t>)>>(
        'shout_queuelen',
      );
  late final _shout_queuelen =
      _shout_queuelenPtr.asFunction<int Function(ffi.Pointer<shout_t>)>();

  /// Puts caller to sleep until it is time to send more data to the server
  void shout_sync(ffi.Pointer<shout_t> self) {
    return _shout_sync(self);
  }

  late final _shout_syncPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<shout_t>)>>(
        'shout_sync',
      );
  late final _shout_sync =
      _shout_syncPtr.asFunction<void Function(ffi.Pointer<shout_t>)>();

  /// Amount of time in ms caller should wait before sending again
  int shout_delay(ffi.Pointer<shout_t> self) {
    return _shout_delay(self);
  }

  late final _shout_delayPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<shout_t>)>>(
        'shout_delay',
      );
  late final _shout_delay =
      _shout_delayPtr.asFunction<int Function(ffi.Pointer<shout_t>)>();

  /// Sets MP3 metadata.
  /// Returns one of SHOUTERR_XXX.
  ///
  /// Note: This function is for MP3 streams only.
  ///
  /// The metadata passed must have been added as UTF-8 using shout_metadata_add().
  int shout_set_metadata_utf8(
    ffi.Pointer<shout_t> self,
    ffi.Pointer<shout_metadata_t> metadata,
  ) {
    return _shout_set_metadata_utf8(self, metadata);
  }

  late final _shout_set_metadata_utf8Ptr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<shout_t>, ffi.Pointer<shout_metadata_t>)
    >
  >('shout_set_metadata_utf8');
  late final _shout_set_metadata_utf8 =
      _shout_set_metadata_utf8Ptr
          .asFunction<
            int Function(ffi.Pointer<shout_t>, ffi.Pointer<shout_metadata_t>)
          >();

  /// Allocates a new metadata structure.  Must be freed by shout_metadata_free.
  ffi.Pointer<shout_metadata_t> shout_metadata_new() {
    return _shout_metadata_new();
  }

  late final _shout_metadata_newPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<shout_metadata_t> Function()>>(
        'shout_metadata_new',
      );
  late final _shout_metadata_new =
      _shout_metadata_newPtr
          .asFunction<ffi.Pointer<shout_metadata_t> Function()>();

  /// Free resources allocated by shout_metadata_t
  void shout_metadata_free(ffi.Pointer<shout_metadata_t> self) {
    return _shout_metadata_free(self);
  }

  late final _shout_metadata_freePtr = _lookup<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<shout_metadata_t>)>
  >('shout_metadata_free');
  late final _shout_metadata_free =
      _shout_metadata_freePtr
          .asFunction<void Function(ffi.Pointer<shout_metadata_t>)>();

  /// Add a parameter to the metadata structure.
  /// Returns:
  /// SHOUTERR_SUCCESS on success
  /// SHOUTERR_INSANE if self isn't a valid shout_metadata_t* or name is null
  /// SHOUTERR_MALLOC if memory can't be allocated
  int shout_metadata_add(
    ffi.Pointer<shout_metadata_t> self,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Char> value,
  ) {
    return _shout_metadata_add(self, name, value);
  }

  late final _shout_metadata_addPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<shout_metadata_t>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
      )
    >
  >('shout_metadata_add');
  late final _shout_metadata_add =
      _shout_metadata_addPtr
          .asFunction<
            int Function(
              ffi.Pointer<shout_metadata_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
            )
          >();

  /// ----------------[ Advanced ]---------------- */
  /// /* Advanced. Do not use.
  int shout_control(ffi.Pointer<shout_t> self, shout_control_t control) {
    return _shout_control(self, control.value);
  }

  late final _shout_controlPtr = _lookup<
    ffi.NativeFunction<ffi.Int Function(ffi.Pointer<shout_t>, ffi.UnsignedInt)>
  >('shout_control');
  late final _shout_control =
      _shout_controlPtr.asFunction<int Function(ffi.Pointer<shout_t>, int)>();

  int shout_set_callback(
    ffi.Pointer<shout_t> self,
    shout_callback_t callback,
    ffi.Pointer<ffi.Void> userdata,
  ) {
    return _shout_set_callback(self, callback, userdata);
  }

  late final _shout_set_callbackPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<shout_t>,
        shout_callback_t,
        ffi.Pointer<ffi.Void>,
      )
    >
  >('shout_set_callback');
  late final _shout_set_callback =
      _shout_set_callbackPtr
          .asFunction<
            int Function(
              ffi.Pointer<shout_t>,
              shout_callback_t,
              ffi.Pointer<ffi.Void>,
            )
          >();

  /// ----------------[ Obsolete ]---------------- */
  /// /* Those functions are obsolete and MUST NOT be used in newer software.
  /// They may be removed with any future version.
  int shout_set_name(ffi.Pointer<shout_t> self, ffi.Pointer<ffi.Char> name) {
    return _shout_set_name(self, name);
  }

  late final _shout_set_namePtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<shout_t>, ffi.Pointer<ffi.Char>)
    >
  >('shout_set_name');
  late final _shout_set_name =
      _shout_set_namePtr
          .asFunction<
            int Function(ffi.Pointer<shout_t>, ffi.Pointer<ffi.Char>)
          >();

  ffi.Pointer<ffi.Char> shout_get_name(ffi.Pointer<shout_t> self) {
    return _shout_get_name(self);
  }

  late final _shout_get_namePtr = _lookup<
    ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>
  >('shout_get_name');
  late final _shout_get_name =
      _shout_get_namePtr
          .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>();

  int shout_set_url(ffi.Pointer<shout_t> self, ffi.Pointer<ffi.Char> url) {
    return _shout_set_url(self, url);
  }

  late final _shout_set_urlPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<shout_t>, ffi.Pointer<ffi.Char>)
    >
  >('shout_set_url');
  late final _shout_set_url =
      _shout_set_urlPtr
          .asFunction<
            int Function(ffi.Pointer<shout_t>, ffi.Pointer<ffi.Char>)
          >();

  ffi.Pointer<ffi.Char> shout_get_url(ffi.Pointer<shout_t> self) {
    return _shout_get_url(self);
  }

  late final _shout_get_urlPtr = _lookup<
    ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>
  >('shout_get_url');
  late final _shout_get_url =
      _shout_get_urlPtr
          .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>();

  int shout_set_genre(ffi.Pointer<shout_t> self, ffi.Pointer<ffi.Char> genre) {
    return _shout_set_genre(self, genre);
  }

  late final _shout_set_genrePtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<shout_t>, ffi.Pointer<ffi.Char>)
    >
  >('shout_set_genre');
  late final _shout_set_genre =
      _shout_set_genrePtr
          .asFunction<
            int Function(ffi.Pointer<shout_t>, ffi.Pointer<ffi.Char>)
          >();

  ffi.Pointer<ffi.Char> shout_get_genre(ffi.Pointer<shout_t> self) {
    return _shout_get_genre(self);
  }

  late final _shout_get_genrePtr = _lookup<
    ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>
  >('shout_get_genre');
  late final _shout_get_genre =
      _shout_get_genrePtr
          .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>();

  int shout_set_description(
    ffi.Pointer<shout_t> self,
    ffi.Pointer<ffi.Char> description,
  ) {
    return _shout_set_description(self, description);
  }

  late final _shout_set_descriptionPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<shout_t>, ffi.Pointer<ffi.Char>)
    >
  >('shout_set_description');
  late final _shout_set_description =
      _shout_set_descriptionPtr
          .asFunction<
            int Function(ffi.Pointer<shout_t>, ffi.Pointer<ffi.Char>)
          >();

  ffi.Pointer<ffi.Char> shout_get_description(ffi.Pointer<shout_t> self) {
    return _shout_get_description(self);
  }

  late final _shout_get_descriptionPtr = _lookup<
    ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>
  >('shout_get_description');
  late final _shout_get_description =
      _shout_get_descriptionPtr
          .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>();

  /// takes a SHOUT_FORMAT_xxxx argument
  int shout_set_format(ffi.Pointer<shout_t> self, int format) {
    return _shout_set_format(self, format);
  }

  late final _shout_set_formatPtr = _lookup<
    ffi.NativeFunction<ffi.Int Function(ffi.Pointer<shout_t>, ffi.UnsignedInt)>
  >('shout_set_format');
  late final _shout_set_format =
      _shout_set_formatPtr
          .asFunction<int Function(ffi.Pointer<shout_t>, int)>();

  int shout_get_format(ffi.Pointer<shout_t> self) {
    return _shout_get_format(self);
  }

  late final _shout_get_formatPtr = _lookup<
    ffi.NativeFunction<ffi.UnsignedInt Function(ffi.Pointer<shout_t>)>
  >('shout_get_format');
  late final _shout_get_format =
      _shout_get_formatPtr.asFunction<int Function(ffi.Pointer<shout_t>)>();

  int shout_set_dumpfile(
    ffi.Pointer<shout_t> self,
    ffi.Pointer<ffi.Char> dumpfile,
  ) {
    return _shout_set_dumpfile(self, dumpfile);
  }

  late final _shout_set_dumpfilePtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<shout_t>, ffi.Pointer<ffi.Char>)
    >
  >('shout_set_dumpfile');
  late final _shout_set_dumpfile =
      _shout_set_dumpfilePtr
          .asFunction<
            int Function(ffi.Pointer<shout_t>, ffi.Pointer<ffi.Char>)
          >();

  ffi.Pointer<ffi.Char> shout_get_dumpfile(ffi.Pointer<shout_t> self) {
    return _shout_get_dumpfile(self);
  }

  late final _shout_get_dumpfilePtr = _lookup<
    ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>
  >('shout_get_dumpfile');
  late final _shout_get_dumpfile =
      _shout_get_dumpfilePtr
          .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<shout_t>)>();

  int shout_set_metadata(
    ffi.Pointer<shout_t> self,
    ffi.Pointer<shout_metadata_t> metadata,
  ) {
    return _shout_set_metadata(self, metadata);
  }

  late final _shout_set_metadataPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<shout_t>, ffi.Pointer<shout_metadata_t>)
    >
  >('shout_set_metadata');
  late final _shout_set_metadata =
      _shout_set_metadataPtr
          .asFunction<
            int Function(ffi.Pointer<shout_t>, ffi.Pointer<shout_metadata_t>)
          >();
}

enum shout_control_t {
  SHOUT_CONTROL__MIN(0),
  SHOUT_CONTROL_GET_SERVER_CERTIFICATE_AS_PEM(1),
  SHOUT_CONTROL_GET_SERVER_CERTIFICATE_CHAIN_AS_PEM(2),
  SHOUT_CONTROL__MAX(32767);

  final int value;
  const shout_control_t(this.value);

  static shout_control_t fromValue(int value) => switch (value) {
    0 => SHOUT_CONTROL__MIN,
    1 => SHOUT_CONTROL_GET_SERVER_CERTIFICATE_AS_PEM,
    2 => SHOUT_CONTROL_GET_SERVER_CERTIFICATE_CHAIN_AS_PEM,
    32767 => SHOUT_CONTROL__MAX,
    _ => throw ArgumentError("Unknown value for shout_control_t: $value"),
  };
}

enum shout_event_t {
  SHOUT_EVENT__MIN(0),
  SHOUT_EVENT_TLS_CHECK_PEER_CERTIFICATE(1),
  SHOUT_EVENT__MAX(32767);

  final int value;
  const shout_event_t(this.value);

  static shout_event_t fromValue(int value) => switch (value) {
    0 => SHOUT_EVENT__MIN,
    1 => SHOUT_EVENT_TLS_CHECK_PEER_CERTIFICATE,
    32767 => SHOUT_EVENT__MAX,
    _ => throw ArgumentError("Unknown value for shout_event_t: $value"),
  };
}

final class shout extends ffi.Opaque {}

final class _util_dict extends ffi.Opaque {}

typedef shout_t = shout;
typedef ssize_t = __darwin_ssize_t;
typedef __darwin_ssize_t = ffi.Long;
typedef Dart__darwin_ssize_t = int;
typedef shout_metadata_t = _util_dict;
typedef shout_callback_t =
    ffi.Pointer<ffi.NativeFunction<shout_callback_tFunction>>;
typedef shout_callback_tFunction =
    ffi.Int Function(
      ffi.Pointer<shout_t> shout,
      ffi.UnsignedInt event,
      ffi.Pointer<ffi.Void> userdata,
      va_list ap,
    );
typedef Dartshout_callback_tFunction =
    int Function(
      ffi.Pointer<shout_t> shout,
      shout_event_t event,
      ffi.Pointer<ffi.Void> userdata,
      va_list ap,
    );
typedef va_list = __builtin_va_list;
typedef __builtin_va_list = ffi.Pointer<ffi.Char>;

const int SHOUTERR_SUCCESS = 0;

const int SHOUTERR_INSANE = -1;

const int SHOUTERR_NOCONNECT = -2;

const int SHOUTERR_NOLOGIN = -3;

const int SHOUTERR_SOCKET = -4;

const int SHOUTERR_MALLOC = -5;

const int SHOUTERR_METADATA = -6;

const int SHOUTERR_CONNECTED = -7;

const int SHOUTERR_UNCONNECTED = -8;

const int SHOUTERR_UNSUPPORTED = -9;

const int SHOUTERR_BUSY = -10;

const int SHOUTERR_NOTLS = -11;

const int SHOUTERR_TLSBADCERT = -12;

const int SHOUTERR_RETRY = -13;

const int SHOUT_FORMAT_OGG = 0;

const int SHOUT_FORMAT_MP3 = 1;

const int SHOUT_FORMAT_WEBM = 2;

const int SHOUT_FORMAT_WEBMAUDIO = 3;

const int SHOUT_FORMAT_MATROSKA = 4;

const int SHOUT_FORMAT_TEXT = 5;

const int SHOUT_FORMAT_VORBIS = 0;

const int SHOUT_USAGE_AUDIO = 1;

const int SHOUT_USAGE_VISUAL = 2;

const int SHOUT_USAGE_TEXT = 4;

const int SHOUT_USAGE_SUBTITLE = 8;

const int SHOUT_USAGE_LIGHT = 16;

const int SHOUT_USAGE_UI = 32;

const int SHOUT_USAGE_METADATA = 64;

const int SHOUT_USAGE_APPLICATION = 128;

const int SHOUT_USAGE_CONTROL = 256;

const int SHOUT_USAGE_COMPLEX = 512;

const int SHOUT_USAGE_OTHER = 1024;

const int SHOUT_USAGE_UNKNOWN = 2048;

const int SHOUT_USAGE_3D = 4096;

const int SHOUT_USAGE_4D = 8192;

const int SHOUT_PROTOCOL_HTTP = 0;

const int SHOUT_PROTOCOL_XAUDIOCAST = 1;

const int SHOUT_PROTOCOL_ICY = 2;

const int SHOUT_PROTOCOL_ROARAUDIO = 3;

const int SHOUT_TLS_DISABLED = 0;

const int SHOUT_TLS_AUTO = 1;

const int SHOUT_TLS_AUTO_NO_PLAIN = 2;

const int SHOUT_TLS_RFC2818 = 11;

const int SHOUT_TLS_RFC2817 = 12;

const int SHOUT_BLOCKING_DEFAULT = 255;

const int SHOUT_BLOCKING_FULL = 0;

const int SHOUT_BLOCKING_NONE = 1;

const String SHOUT_AI_BITRATE = 'bitrate';

const String SHOUT_AI_SAMPLERATE = 'samplerate';

const String SHOUT_AI_CHANNELS = 'channels';

const String SHOUT_AI_QUALITY = 'quality';

const String SHOUT_META_NAME = 'name';

const String SHOUT_META_URL = 'url';

const String SHOUT_META_GENRE = 'genre';

const String SHOUT_META_DESCRIPTION = 'description';

const String SHOUT_META_IRC = 'irc';

const String SHOUT_META_AIM = 'aim';

const String SHOUT_META_ICQ = 'icq';

const int SHOUT_CALLBACK_PASS = 1;

const int SHOUT_THREADSAFE = 1;

const int SHOUT_TLS = 0;
